import { Country } from "@/types/controversies";

export const COUNTRIES: Record<string, Country> = {
  us: {
    name: "United States",
    keywords: [
      "debt ceiling",
      "tax reform",
      "government shutdown",
      "impeachment",
      "election fraud",
      "Supreme Court",
      "abortion rights",
      "January 6",
      "Trump investigation",
      "classified documents",
      "Federal Reserve",
      "Jerome Powell",
    ],
    searchTerms: [
      "United States",
      "America",
      "Congress",
      "Senate",
      "House",
      "Biden",
      "Trump",
      "Republican",
      "Democrat",
      "GOP",
    ],
    domains:
      "cnn.com,foxnews.com,politico.com,washingtonpost.com,nytimes.com,reuters.com,apnews.com,nbcnews.com,cbsnews.com,abcnews.go.com,wsj.com,npr.org,thehill.com",
  },
  uk: {
    name: "United Kingdom",
    keywords: [
      "Brexit",
      "parliament",
      "prime minister",
      "conservative party",
      "labour party",
      "Scotland independence",
      "Northern Ireland",
      "Tory",
      "constitutional crisis",
    ],
    searchTerms: [
      "United Kingdom",
      "Britain",
      "UK",
      "Parliament",
      "Westminster",
      "Downing Street",
      "Conservative",
      "Labour",
      "Tory",
    ],
    domains:
      "bbc.com,theguardian.com,telegraph.co.uk,independent.co.uk,sky.com,reuters.com",
  },
  fr: {
    name: "France",
    keywords: [
      "Emmanuel Macron",
      "parliament",
      "pension reform",
      "yellow vests",
      "Marine Le Pen",
      "immigration",
      "European Union",
      "riots",
    ],
    searchTerms: [
      "France",
      "French",
      "Paris",
      "Macron",
      "Assemblée",
      "République",
      "EU",
      "European Union",
    ],
    domains:
      "lemonde.fr,lefigaro.fr,liberation.fr,franceinfo.fr,reuters.com,france24.com",
  },
  de: {
    name: "Germany",
    keywords: [
      "coalition government",
      "bundestag",
      "Angela Merkel",
      "Olaf Scholz",
      "AfD",
      "immigration",
      "energy crisis",
      "Russia sanctions",
    ],
    searchTerms: [
      "Germany",
      "German",
      "Berlin",
      "Bundestag",
      "Chancellor",
      "CDU",
      "SPD",
      "AfD",
    ],
    domains: "spiegel.de,zeit.de,faz.net,sueddeutsche.de,reuters.com,dw.com",
  },
  cn: {
    name: "China",
    keywords: [
      "Xi Jinping",
      "Communist Party",
      "Hong Kong",
      "Taiwan",
      "Xinjiang",
      "trade war",
      "censorship",
      "protests",
      "human rights",
    ],
    searchTerms: [
      "China",
      "Chinese",
      "Beijing",
      "Communist Party",
      "Xi Jinping",
      "CCP",
      "Taiwan",
      "Hong Kong",
    ],
    domains: "reuters.com,apnews.com,bbc.com,cnn.com,wsj.com,ft.com",
  },
  ru: {
    name: "Russia",
    keywords: [
      "Putin",
      "Ukraine war",
      "sanctions",
      "opposition",
      "Kremlin",
      "election",
      "protests",
      "oligarchs",
      "corruption",
    ],
    searchTerms: [
      "Russia",
      "Russian",
      "Moscow",
      "Putin",
      "Kremlin",
      "Ukraine",
      "sanctions",
    ],
    domains: "reuters.com,apnews.com,bbc.com,cnn.com,wsj.com,ft.com",
  },
  in: {
    name: "India",
    keywords: [
      "Modi",
      "BJP",
      "Congress",
      "Kashmir",
      "farmers protest",
      "citizenship law",
      "Hindu nationalism",
      "parliament",
    ],
    searchTerms: [
      "India",
      "Indian",
      "New Delhi",
      "Modi",
      "BJP",
      "Congress",
      "Parliament",
    ],
    domains:
      "timesofindia.indiatimes.com,hindustantimes.com,indianexpress.com,reuters.com,bbc.com",
  },
  br: {
    name: "Brazil",
    keywords: [
      "Bolsonaro",
      "Lula",
      "Amazon",
      "corruption",
      "Supreme Court",
      "election",
      "military",
      "democracy",
    ],
    searchTerms: [
      "Brazil",
      "Brazilian",
      "Brasilia",
      "Bolsonaro",
      "Lula",
      "Congress",
    ],
    domains: "reuters.com,apnews.com,bbc.com,cnn.com",
  },
  jp: {
    name: "Japan",
    keywords: [
      "LDP",
      "prime minister",
      "constitution",
      "North Korea",
      "China tensions",
      "election",
      "Fukushima",
      "defense spending",
    ],
    searchTerms: [
      "Japan",
      "Japanese",
      "Tokyo",
      "Diet",
      "LDP",
      "Prime Minister",
    ],
    domains: "japantimes.co.jp,nhk.or.jp,reuters.com,bbc.com",
  },
  ca: {
    name: "Canada",
    keywords: [
      "Trudeau",
      "parliament",
      "conservative party",
      "Quebec",
      "indigenous rights",
      "pipeline",
      "election",
      "carbon tax",
    ],
    searchTerms: [
      "Canada",
      "Canadian",
      "Ottawa",
      "Trudeau",
      "Parliament",
      "Conservative",
      "Liberal",
    ],
    domains: "cbc.ca,globalnews.ca,theglobeandmail.com,reuters.com",
  },
  au: {
    name: "Australia",
    keywords: [
      "parliament",
      "labor party",
      "liberal party",
      "climate change",
      "mining",
      "China relations",
      "election",
    ],
    searchTerms: [
      "Australia",
      "Australian",
      "Canberra",
      "Parliament",
      "Labor",
      "Liberal",
    ],
    domains: "abc.net.au,news.com.au,theaustralian.com.au,reuters.com",
  },
  mx: {
    name: "Mexico",
    keywords: [
      "AMLO",
      "MORENA",
      "corruption",
      "cartels",
      "immigration",
      "election",
      "congress",
    ],
    searchTerms: [
      "Mexico",
      "Mexican",
      "Mexico City",
      "AMLO",
      "MORENA",
      "Congress",
    ],
    domains: "reuters.com,apnews.com,bbc.com",
  },
  kr: {
    name: "South Korea",
    keywords: [
      "president",
      "National Assembly",
      "North Korea",
      "impeachment",
      "corruption",
      "chaebol",
      "election",
    ],
    searchTerms: [
      "South Korea",
      "Korean",
      "Seoul",
      "President",
      "National Assembly",
    ],
    domains: "koreatimes.co.kr,koreaherald.com,reuters.com,bbc.com",
  },
  it: {
    name: "Italy",
    keywords: [
      "Giorgia Meloni",
      "parliament",
      "coalition",
      "EU",
      "immigration",
      "Matteo Salvini",
      "election",
    ],
    searchTerms: [
      "Italy",
      "Italian",
      "Rome",
      "Parliament",
      "EU",
      "European Union",
    ],
    domains: "reuters.com,apnews.com,bbc.com",
  },
  es: {
    name: "Spain",
    keywords: [
      "Pedro Sanchez",
      "parliament",
      "Catalonia",
      "independence",
      "PP",
      "PSOE",
      "Vox",
      "election",
    ],
    searchTerms: ["Spain", "Spanish", "Madrid", "Parliament", "Catalonia"],
    domains: "reuters.com,apnews.com,bbc.com",
  },
  ar: {
    name: "Argentina",
    keywords: [
      "president",
      "congress",
      "inflation",
      "IMF",
      "Peronism",
      "economic crisis",
      "election",
    ],
    searchTerms: ["Argentina", "Argentine", "Buenos Aires", "Congress"],
    domains: "reuters.com,apnews.com,bbc.com",
  },
  za: {
    name: "South Africa",
    keywords: [
      "ANC",
      "parliament",
      "corruption",
      "load shedding",
      "EFF",
      "DA",
      "election",
      "Ramaphosa",
    ],
    searchTerms: [
      "South Africa",
      "African",
      "Cape Town",
      "Johannesburg",
      "ANC",
      "Parliament",
    ],
    domains: "reuters.com,apnews.com,bbc.com",
  },
  ng: {
    name: "Nigeria",
    keywords: [
      "president",
      "National Assembly",
      "Boko Haram",
      "corruption",
      "oil",
      "election",
      "security",
    ],
    searchTerms: ["Nigeria", "Nigerian", "Abuja", "Lagos", "National Assembly"],
    domains: "reuters.com,apnews.com,bbc.com",
  },
  eg: {
    name: "Egypt",
    keywords: [
      "Sisi",
      "parliament",
      "human rights",
      "military",
      "Muslim Brotherhood",
      "economy",
      "protests",
    ],
    searchTerms: ["Egypt", "Egyptian", "Cairo", "Sisi", "Parliament"],
    domains: "reuters.com,apnews.com,bbc.com",
  },
  tr: {
    name: "Turkey",
    keywords: [
      "Erdogan",
      "parliament",
      "opposition",
      "election",
      "military",
      "Syria",
      "human rights",
      "economy",
    ],
    searchTerms: [
      "Turkey",
      "Turkish",
      "Ankara",
      "Istanbul",
      "Erdogan",
      "Parliament",
    ],
    domains: "reuters.com,apnews.com,bbc.com",
  },
};
