import { Country } from "@/types/controversies";

export const LANGUAGE_CODES: Record<string, string> = {
  es: "es",
  mx: "es",
  ar: "es",
  fr: "fr",
  de: "de",
  it: "it",
  br: "pt",
  ru: "ru",
  cn: "zh",
  jp: "ja",
  kr: "ko",
  eg: "ar",
  tr: "tr",
  default: "en",
};

export const POLITICAL_TERMS: Record<string, string[]> = {
  es: [
    "política",
    "político",
    "gobierno",
    "ministro",
    "parlamento",
    "congreso",
    "senado",
    "elecciones",
    "controversia",
    "escándalo",
    "debate",
  ],
  fr: [
    "politique",
    "gouvernement",
    "ministre",
    "parlement",
    "élection",
    "controverse",
    "scandale",
    "débat",
  ],
  de: [
    "Politik",
    "Regierung",
    "Minister",
    "Parlament",
    "Wahl",
    "Kontroverse",
    "Skandal",
    "Debatte",
  ],
  it: [
    "politica",
    "governo",
    "ministro",
    "parlamento",
    "elezioni",
    "controversia",
    "scandalo",
    "dibattito",
  ],
  br: [
    "política",
    "governo",
    "ministro",
    "parlamento",
    "eleições",
    "controvérsia",
    "escândalo",
    "debate",
  ],
  ru: [
    "политика",
    "правительство",
    "министр",
    "парламент",
    "выборы",
    "противоречие",
    "скандал",
    "дебаты",
  ],
  cn: ["政治", "政府", "部长", "议会", "选举", "争议", "丑闻", "辩论"],
  jp: ["政治", "政府", "大臣", "議会", "選挙", "論争", "スキャンダル", "討論"],
  kr: ["정치", "정부", "장관", "의회", "선거", "논란", "스캔들", "토론"],
  eg: [
    "السياسة",
    "الحكومة",
    "وزير",
    "البرلمان",
    "انتخابات",
    "جدل",
    "فضيحة",
    "نقاش",
  ],
  tr: [
    "siyaset",
    "hükümet",
    "bakan",
    "parlamento",
    "seçim",
    "tartışma",
    "skandal",
    "tartışma",
  ],
  default: [
    "politics",
    "political",
    "government",
    "minister",
    "parliament",
    "congress",
    "senate",
    "election",
    "controversy",
    "scandal",
    "debate",
  ],
};

export const COUNTRIES: Record<string, Country> = {
  us: {
    name: "United States",
    keywords: [
      "debt ceiling",
      "tax reform",
      "government shutdown",
      "impeachment",
      "election fraud",
      "Supreme Court",
      "abortion rights",
      "January 6",
      "Trump investigation",
      "classified documents",
      "Federal Reserve",
      "Jerome Powell",
    ],
    searchTerms: [
      "United States",
      "America",
      "Congress",
      "Senate",
      "House",
      "Biden",
      "Trump",
      "Republican",
      "Democrat",
      "GOP",
    ],
    domains: [
      "cnn.com",
      "foxnews.com",
      "politico.com",
      "washingtonpost.com",
      "nytimes.com",
      "reuters.com",
      "apnews.com",
      "nbcnews.com",
      "cbsnews.com",
      "abcnews.go.com",
      "wsj.com",
      "npr.org",
      "thehill.com",
    ],
  },
  uk: {
    name: "United Kingdom",
    keywords: [
      "Brexit",
      "parliament",
      "prime minister",
      "conservative party",
      "labour party",
      "Scotland independence",
      "Northern Ireland",
      "Tory",
      "constitutional crisis",
    ],
    searchTerms: [
      "United Kingdom",
      "Britain",
      "UK",
      "Parliament",
      "Westminster",
      "Downing Street",
      "Conservative",
      "Labour",
      "Tory",
    ],
    domains: [
      "bbc.com",
      "theguardian.com",
      "telegraph.co.uk",
      "independent.co.uk",
      "sky.com",
      "reuters.com",
    ],
  },
  fr: {
    name: "France",
    keywords: [
      "Emmanuel Macron",
      "Parlement",
      "Assemblée nationale",
      "réforme des retraites",
      "gilets jaunes",
      "Marine Le Pen",
      "immigration",
      "Union européenne",
      "émeutes",
      "gouvernement",
      "politique",
      "ministre",
      "élections",
    ],
    searchTerms: [
      "France",
      "français",
      "Paris",
      "Macron",
      "Assemblée",
      "République",
      "UE",
    ],
    domains: [
      "lemonde.fr",
      "lefigaro.fr",
      "liberation.fr",
      "franceinfo.fr",
      "france24.com",
      "bfmtv.com",
    ],
  },
  de: {
    name: "Germany",
    keywords: [
      "Koalitionsregierung",
      "Bundestag",
      "Angela Merkel",
      "Olaf Scholz",
      "AfD",
      "Einwanderung",
      "Energiekrise",
      "Russland Sanktionen",
      "Regierung",
      "Politik",
      "Minister",
      "Wahlen",
      "Parlament",
      "Kanzler",
    ],
    searchTerms: [
      "Deutschland",
      "deutsch",
      "Berlin",
      "Bundestag",
      "Kanzler",
      "CDU",
      "SPD",
      "AfD",
    ],
    domains: [
      "spiegel.de",
      "zeit.de",
      "faz.net",
      "sueddeutsche.de",
      "welt.de",
      "tagesschau.de",
      "focus.de",
    ],
  },
  cn: {
    name: "China",
    keywords: [
      "习近平",
      "共产党",
      "香港",
      "台湾",
      "新疆",
      "贸易战",
      "审查制度",
      "抗议",
      "人权",
      "政府",
      "政治",
      "部长",
      "选举",
      "国务院",
    ],
    searchTerms: [
      "中国",
      "中文",
      "北京",
      "共产党",
      "习近平",
      "中共",
      "台湾",
      "香港",
    ],
    domains: [
      "xinhuanet.com",
      "people.com.cn",
      "chinanews.com",
      "china.com",
      "qq.com",
      "sohu.com",
    ],
  },
  ru: {
    name: "Russia",
    keywords: [
      "Путин",
      "война Украина",
      "санкции",
      "оппозиция",
      "Кремль",
      "выборы",
      "протесты",
      "олигархи",
      "коррупция",
      "правительство",
      "политика",
      "министр",
      "дума",
      "парламент",
    ],
    searchTerms: [
      "Россия",
      "российский",
      "Москва",
      "Путин",
      "Кремль",
      "Украина",
      "санкции",
    ],
    domains: [
      "rt.com",
      "ria.ru",
      "tass.ru",
      "gazeta.ru",
      "kommersant.ru",
      "vedomosti.ru",
      "lenta.ru",
    ],
  },
  in: {
    name: "India",
    keywords: [
      "Modi",
      "BJP",
      "Congress",
      "Kashmir",
      "farmers protest",
      "citizenship law",
      "Hindu nationalism",
      "parliament",
    ],
    searchTerms: [
      "India",
      "Indian",
      "New Delhi",
      "Modi",
      "BJP",
      "Congress",
      "Parliament",
    ],
    domains: [
      "timesofindia.indiatimes.com",
      "hindustantimes.com",
      "indianexpress.com",
      "reuters.com",
      "bbc.com",
    ],
  },
  br: {
    name: "Brazil",
    keywords: [
      "Bolsonaro",
      "Lula",
      "Amazônia",
      "corrupção",
      "Supremo Tribunal",
      "eleições",
      "militar",
      "democracia",
      "governo",
      "política",
      "ministro",
      "congresso",
      "presidente",
      "senado",
    ],
    searchTerms: [
      "Brasil",
      "brasileiro",
      "Brasília",
      "Bolsonaro",
      "Lula",
      "Congresso",
    ],
    domains: [
      "globo.com",
      "uol.com.br",
      "folha.uol.com.br",
      "estadao.com.br",
      "g1.globo.com",
      "veja.abril.com.br",
    ],
  },
  jp: {
    name: "Japan",
    keywords: [
      "自民党",
      "首相",
      "憲法",
      "北朝鮮",
      "中国緊張",
      "選挙",
      "福島",
      "防衛費",
      "政府",
      "政治",
      "大臣",
      "国会",
      "議会",
      "党",
    ],
    searchTerms: ["日本", "日本語", "東京", "国会", "自民党", "首相"],
    domains: [
      "asahi.com",
      "yomiuri.co.jp",
      "mainichi.jp",
      "sankei.com",
      "nikkei.com",
      "nhk.or.jp",
    ],
  },
  ca: {
    name: "Canada",
    keywords: [
      "Trudeau",
      "parliament",
      "conservative party",
      "Quebec",
      "indigenous rights",
      "pipeline",
      "election",
      "carbon tax",
    ],
    searchTerms: [
      "Canada",
      "Canadian",
      "Ottawa",
      "Trudeau",
      "Parliament",
      "Conservative",
      "Liberal",
    ],
    domains: ["cbc.ca", "globalnews.ca", "theglobeandmail.com", "reuters.com"],
  },
  au: {
    name: "Australia",
    keywords: [
      "parliament",
      "labor party",
      "liberal party",
      "climate change",
      "mining",
      "China relations",
      "election",
    ],
    searchTerms: [
      "Australia",
      "Australian",
      "Canberra",
      "Parliament",
      "Labor",
      "Liberal",
    ],
    domains: [
      "abc.net.au",
      "news.com.au",
      "theaustralian.com.au",
      "reuters.com",
    ],
  },
  mx: {
    name: "Mexico",
    keywords: [
      "AMLO",
      "MORENA",
      "corrupción",
      "cárteles",
      "inmigración",
      "elecciones",
      "congreso",
      "gobierno",
      "política",
      "ministro",
      "presidente",
      "senado",
      "diputados",
    ],
    searchTerms: [
      "México",
      "mexicano",
      "Ciudad de México",
      "AMLO",
      "MORENA",
      "Congreso",
    ],
    domains: [
      "eluniversal.com.mx",
      "milenio.com",
      "excelsior.com.mx",
      "jornada.com.mx",
      "reforma.com",
      "proceso.com.mx",
    ],
  },
  kr: {
    name: "South Korea",
    keywords: [
      "대통령",
      "국회",
      "북한",
      "탄핵",
      "부패",
      "재벌",
      "선거",
      "정부",
      "정치",
      "장관",
      "의회",
      "당",
    ],
    searchTerms: ["한국", "한국어", "서울", "대통령", "국회"],
    domains: [
      "chosun.com",
      "joongang.co.kr",
      "donga.com",
      "hani.co.kr",
      "khan.co.kr",
      "ytn.co.kr",
    ],
  },
  it: {
    name: "Italy",
    keywords: [
      "Giorgia Meloni",
      "parlamento",
      "coalizione",
      "UE",
      "immigrazione",
      "Matteo Salvini",
      "elezioni",
      "governo",
      "politica",
      "ministro",
      "senato",
      "camera",
      "partito",
    ],
    searchTerms: [
      "Italia",
      "italiano",
      "Roma",
      "Parlamento",
      "UE",
      "Unione Europea",
    ],
    domains: [
      "corriere.it",
      "repubblica.it",
      "gazzetta.it",
      "ansa.it",
      "ilsole24ore.com",
      "lastampa.it",
    ],
  },
  es: {
    name: "Spain",
    keywords: [
      "Pedro Sánchez",
      "Parlamento",
      "Cataluña",
      "independencia",
      "Partido Popular",
      "PSOE",
      "Vox",
      "elecciones",
      "gobierno",
      "política",
      "Congreso",
      "Senado",
      "Generalitat",
      "autonomías",
    ],
    searchTerms: [
      "España",
      "español",
      "Madrid",
      "Parlamento",
      "Cataluña",
      "Valencia",
      "País Vasco",
    ],
    domains: [
      "elpais.com",
      "elmundo.es",
      "abc.es",
      "lavanguardia.com",
      "elperiodico.com",
      "20minutos.es",
      "rtve.es",
    ],
  },
  ar: {
    name: "Argentina",
    keywords: [
      "presidente",
      "congreso",
      "inflación",
      "FMI",
      "Peronismo",
      "crisis económica",
      "elecciones",
      "gobierno",
      "política",
      "ministro",
      "senado",
      "diputados",
      "kirchnerismo",
    ],
    searchTerms: ["Argentina", "argentino", "Buenos Aires", "Congreso"],
    domains: [
      "clarin.com",
      "lanacion.com.ar",
      "pagina12.com.ar",
      "infobae.com",
      "ambito.com",
      "perfil.com",
    ],
  },
  za: {
    name: "South Africa",
    keywords: [
      "ANC",
      "parliament",
      "corruption",
      "load shedding",
      "EFF",
      "DA",
      "election",
      "Ramaphosa",
    ],
    searchTerms: [
      "South Africa",
      "African",
      "Cape Town",
      "Johannesburg",
      "ANC",
      "Parliament",
    ],
    domains: ["reuters.com", "apnews.com", "bbc.com"],
  },
  ng: {
    name: "Nigeria",
    keywords: [
      "president",
      "National Assembly",
      "Boko Haram",
      "corruption",
      "oil",
      "election",
      "security",
    ],
    searchTerms: ["Nigeria", "Nigerian", "Abuja", "Lagos", "National Assembly"],
    domains: ["reuters.com", "apnews.com", "bbc.com"],
  },
  eg: {
    name: "Egypt",
    keywords: [
      "السيسي",
      "البرلمان",
      "حقوق الإنسان",
      "الجيش",
      "الإخوان المسلمون",
      "الاقتصاد",
      "احتجاجات",
      "الحكومة",
      "السياسة",
      "وزير",
      "انتخابات",
      "مجلس النواب",
    ],
    searchTerms: ["مصر", "مصري", "القاهرة", "السيسي", "البرلمان"],
    domains: [
      "ahram.org.eg",
      "youm7.com",
      "masrawy.com",
      "elwatannews.com",
      "dostor.org",
      "almasryalyoum.com",
    ],
  },
  tr: {
    name: "Turkey",
    keywords: [
      "Erdoğan",
      "parlamento",
      "muhalefet",
      "seçim",
      "asker",
      "Suriye",
      "insan hakları",
      "ekonomi",
      "hükümet",
      "siyaset",
      "bakan",
      "meclis",
      "parti",
    ],
    searchTerms: [
      "Türkiye",
      "Türk",
      "Ankara",
      "İstanbul",
      "Erdoğan",
      "Parlamento",
    ],
    domains: [
      "hurriyet.com.tr",
      "sabah.com.tr",
      "milliyet.com.tr",
      "sozcu.com.tr",
      "haberturk.com",
      "ntv.com.tr",
    ],
  },
  id: {
    name: "Indonesia",
    keywords: [
      "Jokowi",
      "parlemen",
      "demokrasi",
      "korupsi",
      "pemilu",
      "pemerintah",
      "politik",
      "menteri",
      "DPR",
      "presiden",
    ],
    searchTerms: ["Indonesia", "Jakarta", "Jokowi", "parlemen"],
    domains: [
      "detik.com",
      "kompas.com",
      "liputan6.com",
      "tempo.co",
      "republika.co.id",
      "antara.co.id",
    ],
  },
  pk: {
    name: "Pakistan",
    keywords: [
      "prime minister",
      "parliament",
      "military",
      "corruption",
      "election",
      "Kashmir",
      "terrorism",
      "economy",
    ],
    searchTerms: ["Pakistan", "Islamabad", "Karachi", "parliament"],
    domains: ["dawn.com", "geo.tv", "tribune.com.pk", "reuters.com", "bbc.com"],
  },
  bd: {
    name: "Bangladesh",
    keywords: [
      "parliament",
      "prime minister",
      "election",
      "democracy",
      "garment industry",
      "corruption",
      "protests",
    ],
    searchTerms: ["Bangladesh", "Dhaka", "parliament"],
    domains: ["prothomalo.com", "thedailystar.net", "reuters.com", "bbc.com"],
  },
  sa: {
    name: "Saudi Arabia",
    keywords: [
      "Mohammed bin Salman",
      "Vision 2030",
      "oil",
      "human rights",
      "Yemen",
      "economy",
      "reforms",
    ],
    searchTerms: ["Saudi Arabia", "Riyadh", "MBS", "kingdom"],
    domains: [
      "arabnews.com",
      "saudigazette.com.sa",
      "spa.gov.sa",
      "reuters.com",
    ],
  },
  il: {
    name: "Israel",
    keywords: [
      "Netanyahu",
      "Knesset",
      "Palestine",
      "Gaza",
      "West Bank",
      "election",
      "coalition",
      "security",
    ],
    searchTerms: ["Israel", "Jerusalem", "Tel Aviv", "Netanyahu", "Knesset"],
    domains: [
      "haaretz.com",
      "jpost.com",
      "timesofisrael.com",
      "ynetnews.com",
      "reuters.com",
    ],
  },
  ua: {
    name: "Ukraine",
    keywords: [
      "Zelensky",
      "war",
      "Russia",
      "parliament",
      "NATO",
      "EU",
      "reconstruction",
      "corruption",
    ],
    searchTerms: ["Ukraine", "Kyiv", "Kiev", "Zelensky", "parliament"],
    domains: [
      "kyivindependent.com",
      "ukrinform.net",
      "pravda.com.ua",
      "reuters.com",
      "bbc.com",
    ],
  },
  th: {
    name: "Thailand",
    keywords: [
      "parliament",
      "monarchy",
      "military coup",
      "democracy",
      "election",
      "protests",
      "economy",
    ],
    searchTerms: ["Thailand", "Bangkok", "parliament"],
    domains: [
      "bangkokpost.com",
      "thaivisa.com",
      "nationthailand.com",
      "reuters.com",
    ],
  },
  pl: {
    name: "Poland",
    keywords: [
      "sejm",
      "PiS",
      "Tusk",
      "Duda",
      "UE",
      "sądy",
      "wybory",
      "rząd",
      "polityka",
      "minister",
      "parlament",
    ],
    searchTerms: ["Polska", "Warszawa", "sejm", "rząd"],
    domains: [
      "onet.pl",
      "gazeta.pl",
      "wp.pl",
      "tvn24.pl",
      "rp.pl",
      "polsatnews.pl",
    ],
  },
  nl: {
    name: "Netherlands",
    keywords: [
      "parliament",
      "coalition",
      "VVD",
      "election",
      "EU",
      "immigration",
      "climate",
      "government",
    ],
    searchTerms: [
      "Netherlands",
      "Holland",
      "Amsterdam",
      "The Hague",
      "parliament",
    ],
    domains: [
      "nos.nl",
      "nu.nl",
      "volkskrant.nl",
      "telegraaf.nl",
      "reuters.com",
    ],
  },
  se: {
    name: "Sweden",
    keywords: [
      "parliament",
      "Social Democrats",
      "Moderates",
      "immigration",
      "EU",
      "NATO",
      "election",
      "government",
    ],
    searchTerms: ["Sweden", "Stockholm", "parliament", "riksdag"],
    domains: [
      "svt.se",
      "dn.se",
      "aftonbladet.se",
      "expressen.se",
      "reuters.com",
    ],
  },
};
